<!doctype html>
<meta charset="utf-8">
<link rel="stylesheet" href="../../static/style.css">
<title>Destructors Are Not Always Called in Case of Exceptions! â€” Gergelim</title>
<body>
  <header>
    <h1>Gergelim</h1>
    <nav>
      <ul class="nav navbar-nav">
        <li><a href="../../">Welcome</a></li>
        
          <li class="active"><a href="../">Blog</a></li>
        
          <li><a href="../../projects/">Projects</a></li>
        
          <li><a href="../../about/">About</a></li>
        
      </ul>
    </nav>
  </header>
  <div class="page">
    
  
  <div class="blog-post">
  
    <h2>Destructors Are Not Always Called in Case of Exceptions!</h2>
  
  <p class="meta">
    written by
    
      <a href="https://twitter.com/increatore">Gian</a>
    
    on 2016-06-05
  </p>
  <p>Wrong assumption: when an exception occurs, a stack unwinding occurs, which means that the relevant destructors of objects are called in the appropriate order.</p>
<!-- more -->

<h2>My wrong assumption</h2>
<p>Suppose we have this snippet:</p>
<div class="hll"><pre><span></span><span class="k">struct</span> <span class="nc">A</span> <span class="p">{</span>
    <span class="p">[[</span> <span class="n">noreturn</span> <span class="p">]]</span> <span class="kt">void</span> <span class="n">op</span><span class="p">()</span> <span class="p">{</span> <span class="k">throw</span> <span class="mi">1</span><span class="p">;</span> <span class="p">}</span>
    <span class="o">~</span><span class="n">A</span><span class="p">()</span> <span class="p">{</span> <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span class="s">&quot;Deleting obj...</span><span class="se">\n</span><span class="s">&quot;</span><span class="p">;</span> <span class="p">}</span>
<span class="p">};</span>

<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span> <span class="p">{</span>
  <span class="n">A</span> <span class="n">a</span><span class="p">;</span>
  <span class="n">a</span><span class="p">.</span><span class="n">op</span><span class="p">();</span>   <span class="c1">// The dtor might never be called!</span>
<span class="p">}</span>
</pre></div>
<p>Is <code>a</code>'s destructor called when the exception is thrown? I thought so; I was wrong. This is the output of the snippet above:</p>
<pre>
terminate called after throwing an instance of 'int'
Aborted (core dumped)
</pre><h2>Explanation</h2>
<p>When <code>op()</code> is called, the exception is thrown, and there is no handle for it; it gets out of the main function, so that <code>std::terminate</code> is called and the program aborts (see this <a href="http://stackoverflow.com/a/12887534/382880">question on StackOverflow</a>). From the standard (<code>[except.throw]</code>):</p>
<blockquote><p>When an exception is thrown, control is transferred to the nearest handler with a matching type; "nearest" means the handler for which the <em>compound-statement</em> or <em>ctor-initializer</em> following the <code>try</code> keyword was most recently entered by the thread of control and not yet exited.</p>
</blockquote>
<p>and later on:</p>
<blockquote><p>If no matching handler is found, the function <code>std::terminate()</code> is called; whether or not the stack is unwound before this call to <code>std::terminate()</code> is implementation-defined</p>
</blockquote>
<h2>Correction</h2>
<p>A way to have this exception handled is to wrap the construction of A and the call to <code>op()</code> into a <code>try</code> block:</p>
<div class="hll"><pre><span></span><span class="k">struct</span> <span class="nc">A</span> <span class="p">{</span>
    <span class="p">[[</span> <span class="n">noreturn</span> <span class="p">]]</span> <span class="kt">void</span> <span class="n">op</span><span class="p">()</span> <span class="p">{</span> <span class="k">throw</span> <span class="mi">1</span><span class="p">;</span> <span class="p">}</span>
    <span class="o">~</span><span class="n">A</span><span class="p">()</span> <span class="p">{</span> <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span class="s">&quot;Deleting obj...</span><span class="se">\n</span><span class="s">&quot;</span><span class="p">;</span> <span class="p">}</span>
<span class="p">};</span>

<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span> <span class="p">{</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="n">A</span> <span class="n">a</span><span class="p">;</span>
    <span class="n">a</span><span class="p">.</span><span class="n">op</span><span class="p">();</span>   <span class="c1">// the dtor is guaranteed to be called</span>
  <span class="p">}</span> <span class="k">catch</span><span class="p">(...)</span> <span class="p">{</span>
    <span class="k">throw</span><span class="p">;</span>
  <span class="p">}</span>
<span class="p">}</span>
</pre></div>
<pre>
Deleting obj...
terminate called after throwing an instance of 'int'
Aborted (core dumped)
</pre><p>Notice that just putting the constructor of <code>A</code> out of the <code>try</code> gets us back to the destructor not being called! Read carefully the first snippet from the standard:</p>
<blockquote><p>... "nearest" means the handler for which the compound-statement or ctor-initializer <strong>following</strong> the <code>try</code> keyword.</p>
</blockquote>
<p>So if we had:</p>
<div class="hll"><pre><span></span><span class="c1">// This might not call the dtor!</span>
<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span> <span class="p">{</span>
  <span class="n">A</span> <span class="n">a</span><span class="p">;</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="n">a</span><span class="p">.</span><span class="n">op</span><span class="p">();</span>
  <span class="p">}</span> <span class="k">catch</span><span class="p">(...)</span> <span class="p">{</span>
    <span class="k">throw</span><span class="p">;</span>
  <span class="p">}</span>
<span class="p">}</span>
</pre></div>
<p>there would be no ctor-initializer (nor compound-statement, but that wasn't there before either) after the <code>try</code>.</p>
<p>Apparently, whether or not the stack is unwound is implementation-defined, meaning that on other configurations the result of my experiment wouldn't be the same. But why risking?</p>

  </div>


  </div>
  <footer>
    &copy; Copyright 2021 by Gianluca Ciccarelli.
  </footer>
</body>
